%% 
function [net] = train_MATLAB_nn(data, label, M)
    layers = [
    imageInputLayer([1 1 M-1]);
    fullyConnectedLayer(200)
    layerNormalizationLayer
    tanhLayer
    fullyConnectedLayer(100)
    tanhLayer
    fullyConnectedLayer(50)
    tanhLayer
    fullyConnectedLayer(10)
    tanhLayer
    fullyConnectedLayer(2)
    softmaxLayer
    classificationLayer];

    miniBatchSize = 50;
    options = trainingOptions( ...
    'adam', ...
    'ExecutionEnvironment','auto', ... 
    'MiniBatchSize', miniBatchSize, ...
    'LearnRateSchedule',"piecewise", ...
    'InitialLearnRate',1e-3, ...
    'LearnRateDropFactor', 0.300, ...
    'LearnRateDropPeriod', 1, ...
    'Shuffle','every-epoch', ....
    'Plots','training-progress', ...
    'Verbose', true, ...
    'MaxEpochs', 12 ...
    );

   
    x = data;
    ZZ = reshape(x', [1,1,size(x,2), size(x,1)]);
    net = trainNetwork(ZZ, categorical(label), layers, options);
end